### PR TITLE
Added new option to linePlusBarChart to switch the order of the y axis

### PR DESCRIPTION
**Pull request by klangfarbe**
This patch adds a new option for the LinePlusBar chart which allows the user to specify whether the left yAxis should display the bars (default) or the lines:

screen_linebarchart

### CODE REVIEW

**Comment by liquidpele** [comment]
I'm not sure about this one... this seems like a lot of extra complexity for what is a reeeeealy minor thing.

**Comment by klangfarbe** [comment]
Hi,

yes I agree and I would liked a more easier solution. The problem here arises mainly from consistency, specifying the focus (is the bar or the line the main interesting thing) and usability in conjunction with other diagrams. I attached a picture with a concrete example of a monitoring dashboard I am currently developing: Due to consistency a user would expect to see the ratio 0-100% always on the left side of the panels. The data count in the upper left panel is only additional information which is not the main focus. Therefore the left axis should show the ratio which is represented by the lines.

_New:_
screen_linebarchart_correct

_Old:_
screen_linebarchart_wrong

I hope that this example explains the reason for this patch and why I think it is a benefit to the framework. Nevertheless, if you know of a better solution for this we can implement this :)

**Comment by liquidpele** [comment]
Let me get more input... the order of focus is actually a bug several people have complained about....

**Comment by liquidpele** [comment]
This is too out of date to merge now sorry, please re-submit the PR to the novus repo is you want though, cheers!

**Pull request closed without merging**
